### ISSUE TITLE
Research on Braille interface for watch face

### ISSUE THREAD

**Issue by theantariksha** [rohithaug/UCSD-CSE-118-218-Team-G#13]
Check on the following:

- How does the user interact with the standard Braille?
- What are the most common ways of reading Braille (one-hand vs two-hand, fingers, movement)
- What solutions are available for a watch?
- How can we improve the UX?

Do we have the capacity?
- Capitalization
- Numbers

**Comment by jup023** [comment]
- Swipe to right: register letter / move to next letter
- Swipe to up: clear letter / move to previous letter
