### ISSUE TITLE
Implement Braille mapping (basic punctuations)

### ISSUE THREAD

**Issue by jup023** [rohithaug/UCSD-CSE-118-218-Team-G#41]
apostrophe, colon, comma, dollar sign, exclamation point, hyphen, opening parenthesis, closing parenthesis, period, question mark, double opening quotation mark, double closing quotation mark, semicolon

**Comment by theantariksha** [comment]
I think it's better that we focus on only a minimal set initially (period, question mark, comma, exclamation point). What does everyone think?

**Comment by jup023** [comment]
Sounds good. I listed the ones that only require one braille character, but if it is still too much then I can focus on the minimal set in the first place.

**Comment by theantariksha** [comment]
if you've already done it or it's easy to complete then that's great, I just want to make sure you're not overloaded or anything!
